// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCccV2Z9jeutx_u52ljneQGZsGqhMv5O3w',
    appId: '1:1084187943712:web:86e3def96a9a43dbc1ed45',
    messagingSenderId: '1084187943712',
    projectId: 'practical-flutter-crud',
    authDomain: 'practical-flutter-crud.firebaseapp.com',
    storageBucket: 'practical-flutter-crud.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq-tmlmlbsYrXr7USxoZkoiOxyR2rmO0Q',
    appId: '1:1084187943712:android:e30aee97dfc3e76ec1ed45',
    messagingSenderId: '1084187943712',
    projectId: 'practical-flutter-crud',
    storageBucket: 'practical-flutter-crud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiUluDDHkKtlfz9D1pvg7B7kTgbyde70c',
    appId: '1:1084187943712:ios:600c598a7c63802fc1ed45',
    messagingSenderId: '1084187943712',
    projectId: 'practical-flutter-crud',
    storageBucket: 'practical-flutter-crud.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );
}
